---
AWSTemplateFormatVersion: '2010-09-09'
Description: '{"createdOn":"Windows","createdBy":"Amplify","createdWith":"13.0.1","stackType":"custom-customCloudformation","metadata":{"whyContinueWithGen1":""}}'
Parameters:
  env:
    Type: String
  functionhomethermostatChangeStateName:
    Type: String
    Description: Input parameter describing Name attribute for function/homethermostatChangeState
      resource
  functionhomethermostatChangeStateArn:
    Type: String
    Description: Input parameter describing Arn attribute for function/homethermostatChangeState
      resource
  functionhomethermostatChangeStateRegion:
    Type: String
    Description: Input parameter describing Region attribute for function/homethermostatChangeState
      resource
  functionhomethermostatChangeStateLambdaExecutionRole:
    Type: String
    Description: Input parameter describing LambdaExecutionRole attribute for function/homethermostatChangeState
      resource
  functionhomethermostatChangeStateLambdaExecutionRoleArn:
    Type: String
    Description: Input parameter describing LambdaExecutionRoleArn attribute for function/homethermostatChangeState
      resource
  functionhomethermostatStoreTaskTokenArn:
    Type: String
    Description: Input parameter describing Arn attribute for function/homethermostatStoreTaskToken
      resource
  storagehomethermostatScheduledActivityName:
    Type: String
    Description: Input parameter describing Name attribute for storage/homethermostatScheduledActivity
      resource
  storagehomethermostatScheduledActivityArn:
    Type: String
    Description: Input parameter describing Arn attribute for storage/homethermostatScheduledActivity
      resource
  functionhomethermostatStoreTaskTokenName:
    Type: String
    Description: Input parameter describing Name attribute for function/homethermostatStoreTaskToken
      resource
  functionhomethermostatStoreTaskTokenRegion:
    Type: String
    Description: Input parameter describing Region attribute for function/homethermostatStoreTaskToken
      resource
  functionhomethermostatStoreTaskTokenLambdaExecutionRole:
    Type: String
    Description: Input parameter describing LambdaExecutionRole attribute for function/homethermostatStoreTaskToken
      resource
  functionhomethermostatStoreTaskTokenLambdaExecutionRoleArn:
    Type: String
    Description: Input parameter describing LambdaExecutionRoleArn attribute for function/homethermostatStoreTaskToken
      resource
  storagehomethermostatScheduledActivityStreamArn:
    Type: String
    Description: Input parameter describing StreamArn attribute for storage/homethermostatScheduledActivity
      resource
  storagehomethermostatScheduledActivityPartitionKeyName:
    Type: String
    Description: Input parameter describing PartitionKeyName attribute for storage/homethermostatScheduledActivity
      resource
  storagehomethermostatScheduledActivityPartitionKeyType:
    Type: String
    Description: Input parameter describing PartitionKeyType attribute for storage/homethermostatScheduledActivity
      resource
  storagehomethermostatScheduledActivitySortKeyName:
    Type: String
    Description: Input parameter describing SortKeyName attribute for storage/homethermostatScheduledActivity
      resource
  storagehomethermostatScheduledActivitySortKeyType:
    Type: String
    Description: Input parameter describing SortKeyType attribute for storage/homethermostatScheduledActivity
      resource
  storagehomethermostatScheduledActivityRegion:
    Type: String
    Description: Input parameter describing Region attribute for storage/homethermostatScheduledActivity
      resource
Resources:
  temperatureHeatingChangeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: temperatureHeatingChangeInvokeLambda
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - Ref: functionhomethermostatChangeStateArn
                  - Ref: functionhomethermostatStoreTaskTokenArn
        - PolicyName: temperatureHeatingChangeDynamoDB
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                Resource:
                  - Ref: storagehomethermostatScheduledActivityArn
  temperatureHeatingChange:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn:
        Fn::GetAtt:
          - temperatureHeatingChangeRole
          - Arn
      StateMachineName: temperature-heating-change
      Definition:
        Comment: State machine for controlling heating until target temperature is
          reached
        StartAt: TurnOn
        States:
          TurnOn:
            Type: Task
            Resource:
              Ref: functionhomethermostatChangeStateArn
            Parameters:
              executionArn.$: "$$.Execution.Id"
              thingName.$: "$.thingName"
              mode: 'ON'
            ResultPath: "$.turnOnResult"
            Next: WaitForTargetTemperature
          WaitForTargetTemperature:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke.waitForTaskToken
            Parameters:
              FunctionName:
                Ref: functionhomethermostatStoreTaskTokenArn
              Payload:
                taskToken.$: "$$.Task.Token"
                thingName.$: "$.thingName"
                since.$: "$.since"
                dhwTargetTemperature.$: "$.dhwTargetTemperature"
            TimeoutSeconds: 3600
            ResultPath: "$.waitResult"
            Next: TurnOff
          TurnOff:
            Type: Task
            Resource:
              Ref: functionhomethermostatChangeStateArn
            Parameters:
              executionArn.$: "$$.Execution.Id"
              thingName.$: "$.thingName"
              mode: 'OFF'
              since.$: "$.since"
            ResultPath: "$"
            Next: UpdateScheduledActivityUntil
          UpdateScheduledActivityUntil:
            Type: Task
            Resource: arn:aws:states:::dynamodb:updateItem
            Parameters:
              TableName:
                Ref: storagehomethermostatScheduledActivityName
              Key:
                device:
                  S.$: "$.thingName"
                since:
                  N.$: States.Format('{}', $.since)
              UpdateExpression: 'SET #until = :until'
              ExpressionAttributeNames:
                "#until": until
              ExpressionAttributeValues:
                ":until":
                  N.$: States.Format('{}', $.until)
            End: true
Outputs:
  StateMachineArn:
    Value:
      Ref: temperatureHeatingChange
    Description: ARN of the temperature heating change state machine
  StateMachineName:
    Value:
      Fn::GetAtt:
        - temperatureHeatingChange
        - Name
    Description: Name of the temperature heating change state machine
