import {useCallback, useEffect, useRef, useState} from 'react';
import {InvokeCommand, LambdaClient} from '@aws-sdk/client-lambda';
import {DynamoDBClient} from '@aws-sdk/client-dynamodb';
import {GetThingShadowCommand, IoTDataPlaneClient, UpdateThingShadowCommand} from '@aws-sdk/client-iot-data-plane';
import {DynamodbClient, endReasons, modes, statusHelper, StepFunctionsClient} from 'home-thermostat-common';
import {Amplify} from 'aws-amplify';
import {Hub} from 'aws-amplify/utils';
import {Authenticator} from '@aws-amplify/ui-react';
import {fetchAuthSession, signUp} from 'aws-amplify/auth';
import {SFNClient} from '@aws-sdk/client-sfn';

// Components
import Header from './component/header';
import TimelineChart from './component/timeline-chart';
import DhwGraphModal from './component/dhw-graph-modal';
import DeviceCard from './component/device-card';
import HistoryStats from './component/history-stats';
import ScheduleModal from './component/schedule-modal';

import './App.css';
import '@aws-amplify/ui-react/styles.css';
import {hoursMinsToISOString} from "./util/time-helper";
import {subscribeToShadowUpdates} from './util/shadow-updates';
import {DHW_TEMP, IMMERSION, OIL, RELAY_DEVICES, isOil} from './config/devices';
import amplifyOutputs from '../amplify_outputs.json';

const identityPoolId = 'eu-west-1:a2b980af-483f-41fb-ab4a-fcfef938015a';
Amplify.configure({
  Auth: {
    Cognito: {
      identityPoolId: identityPoolId,
      userPoolId: 'eu-west-1_kaR3nNFXA',
      userPoolClientId: 'pj9peastf76fjjhm1cl1jumpf',
      signUpVerificationMethod: 'link'
    }
  }
});

// Resource names come from the Gen 2 backend rather than being hardcoded, so the sandbox and the
// deployed branch each talk to their own lambda/state machine. amplify_outputs.json is generated by
// `ampx sandbox` locally and by `ampx pipeline-deploy` in the backend build phase, which runs before
// the frontend build.
const {
  startScheduleStateChangeFunctionArn: startScheduleStateChangeLambdaArn,
  deviceStateTableName: stateTableName,
  scheduledActivityTableName: scheduleTableName,
  temperatureTableName,
} = amplifyOutputs.custom;
let lambda, dynamodbClient, stepFunctionsClient, iotData;

const App = () => {
  const [scheduleModalShow, setScheduleModalShow] = useState(false);
  const [selectedDevice, setSelectedDevice] = useState(null); // For schedule modal
  const [connected, setConnected] = useState(false);
  const [statuses, setStatuses] = useState([]);
  const [scheduledActivity, setScheduledActivity] = useState([]);
  const [dhwTemperature, setDhwTemperature] = useState(null);
  const [showDhwGraph, setShowDhwGraph] = useState(false);
  const [outsideTemp, setOutsideTemp] = useState(null);
  const [selectedStatsDevice, setSelectedStatsDevice] = useState(null);
  const [signUpPending, setSignUpPending] = useState(false);
  const [credentialsReady, setCredentialsReady] = useState(false);
  const refreshTimerRef = useRef(null);

  // Device-specific statuses
  const [oilStatus, setOilStatus] = useState({mode: 'Loading...'});
  const [immersionStatus, setImmersionStatus] = useState({mode: 'Loading...'});

  useEffect(() => {
    const unsubscribe = Hub.listen('auth', async (data) => {
      // Amplify v6 renamed this event from 'signIn'. Under the old name the app only picked up
      // credentials on a page reload, never straight after signing in.
      if ('signedIn' === data.payload.event) {
        setSignUpPending(false);
        await setUserAndSyncStatus();
      }
    });

    fetchAuthSession().then(() => {
      setUserAndSyncStatus();
    });
    fetchOutsideTemperature();

    return unsubscribe;
  }, []);

  async function fetchOutsideTemperature() {
    try {
      const weatherApiUrl = 'https://api.openweathermap.org/data/2.5/weather?lat=52.9807857&lon=-6.046806&appid=5796abbde9106b7da4febfae8c44c232';
      const response = await fetch(weatherApiUrl);
      const data = await response.json();
      const tempCelsius = Math.round((data.main.temp - 273.15) * 2) / 2;
      setOutsideTemp(tempCelsius);
    } catch (error) {
      console.error('Error fetching outside temperature:', error);
    }
  }

  async function setUserAndSyncStatus() {
    try {
      const session = await fetchAuthSession();
      if (!session.credentials) throw new Error('No credentials available');
      const {accessKeyId, secretAccessKey, sessionToken} = session.credentials;
      const awsCredentials = {
        accessKeyId,
        secretAccessKey,
        sessionToken
      };

      lambda = new LambdaClient({
        region: 'eu-west-1',
        credentials: awsCredentials
      });
      dynamodbClient = new DynamodbClient(new DynamoDBClient({
        region: 'eu-west-1',
        credentials: awsCredentials
      }));
      stepFunctionsClient = new StepFunctionsClient(new SFNClient({
        region: 'eu-west-1',
        credentials: awsCredentials
      }));
      iotData = new IoTDataPlaneClient({
        region: 'eu-west-1',
        endpoint: 'https://a1t0rh7vtg6i19-ats.iot.eu-west-1.amazonaws.com',
        credentials: awsCredentials
      });

      setCredentialsReady(true);
      await syncAllStatuses();
    } catch (error) {
      console.log(error);
    }
  }

  const setterFor = (device) => (isOil(device) ? setOilStatus : setImmersionStatus);

  const queueRefresh = useCallback((delayMs = 750) => {
    clearTimeout(refreshTimerRef.current);
    refreshTimerRef.current = setTimeout(() => {
      Promise.all([
        fetchDhwTemperature(),
        fetchTimelineAndScheduledActivity(),
        fetchHistoricalStatuses()
      ]).catch((error) => console.error('Error refreshing after shadow update:', error));
    }, delayMs);
  }, []);

  /*
   * Any accepted update means something moved, so re-read either way: a desired-only one is this
   * app's own instruction reaching IoT before the state machine has written the status row. Only
   * the device reporting back is trusted to set the mode.
   */
  const applyShadowUpdate = useCallback((device, {reported}) => {
    if (reported?.on !== undefined) {
      setterFor(device)((current) => ({...current, device, mode: reported.on ? modes.ON.val : modes.OFF.val}));
    }

    if (isOil(device) && reported?.connected !== undefined) {
      setConnected(reported.connected);
    }

    queueRefresh();
  }, [queueRefresh]);

  // Picks up changes nobody in this browser made: a state machine ending a run, or the hardware.
  useEffect(() => {
    if (!credentialsReady) return;

    const unsubscribe = subscribeToShadowUpdates(
      RELAY_DEVICES,
      applyShadowUpdate,
      (device, error) => console.error(`Shadow subscription failed for ${device}:`, error)
    );

    return () => {
      clearTimeout(refreshTimerRef.current);
      unsubscribe();
    };
  }, [credentialsReady, applyShadowUpdate]);

  async function syncAllStatuses() {
    // The shadow reports only on/off, so it is read before the DynamoDB statuses that
    // overwrite it with 'until' and 'executionArn'; run together, the shadow can win the race.
    await Promise.all([
      syncDeviceStatus(OIL, setOilStatus),
      syncDeviceStatus(IMMERSION, setImmersionStatus)
    ]);

    await Promise.all([
      fetchDhwTemperature(),
      fetchTimelineAndScheduledActivity(),
      fetchHistoricalStatuses()
    ]);
  }

  /*
   * A thing that has never been connected to has no shadow, and one whose device has never
   * reported has no reported section, so neither can be relied on. What was last asked for is the
   * best available answer in that case, and the device counts as disconnected either way.
   */
  async function syncDeviceStatus(device, setDeviceStatus) {
    try {
      const command = new GetThingShadowCommand({thingName: device, shadowName: device + '_shadow'});
      const data = await iotData.send(command);
      const state = JSON.parse(new TextDecoder().decode(data.payload)).state ?? {};
      const reported = state.reported ?? {};
      const isOn = reported.on ?? state.desired?.on ?? false;

      if (isOil(device)) {
        setConnected(reported.connected ?? false);
      }

      setDeviceStatus({mode: isOn ? modes.ON.val : modes.OFF.val, device: device});
    } catch (error) {
      if (error.name === 'ResourceNotFoundException') {
        if (isOil(device)) {
          setConnected(false);
        }
        setDeviceStatus({mode: modes.OFF.val, device: device});
        return;
      }

      console.error(`Error syncing status for ${device}:`, error);
      setDeviceStatus({mode: 'Error', device: device});
    }
  }

  async function fetchDhwTemperature() {
    try {
      const tempData = await dynamodbClient.getLatestTemperature(temperatureTableName, DHW_TEMP);
      if (tempData) {
        const now = Date.now();
        const tempAge = now - tempData.timestamp;
        const tenMinutes = 10 * 60 * 1000;
        setDhwTemperature({
          temperature: tempData.temperature,
          timestamp: tempData.timestamp,
          isStale: tempAge > tenMinutes
        });
      }
    } catch (error) {
      console.log('Error fetching DHW temperature:', error);
      setDhwTemperature(null);
    }
  }

  // Fetch last 1 day of statuses for timeline AND scheduled activity (both devices)
  async function fetchTimelineAndScheduledActivity() {
    try {
      const oneDayAgo = Math.floor((Date.now() - (24 * 60 * 60 * 1000)) / 1000);

      const [oilStatuses, immersionStatuses, oilScheduled, immersionScheduled] = await Promise.all([
        dynamodbClient.getStatuses(stateTableName, OIL, oneDayAgo),
        dynamodbClient.getStatuses(stateTableName, IMMERSION, oneDayAgo),
        dynamodbClient.getScheduledActivity(scheduleTableName, OIL),
        dynamodbClient.getScheduledActivity(scheduleTableName, IMMERSION)
      ]);

      // Update device statuses with most recent
      if (oilStatuses.length > 0) {
        setOilStatus(oilStatuses[0]);
      }
      if (immersionStatuses.length > 0) {
        setImmersionStatus(immersionStatuses[0]);
      }

      // Drop activities whose execution died without closing them off, otherwise an aborted DHW
      // run is drawn as still heating indefinitely.
      const stillRunning = (scheduled, deviceStatuses) =>
        scheduled.filter((activity) => statusHelper.isScheduledActivityRunning(activity, deviceStatuses));

      const allScheduled = [
        ...stillRunning(oilScheduled, oilStatuses),
        ...stillRunning(immersionScheduled, immersionStatuses)
      ];
      setScheduledActivity(allScheduled);
    } catch (error) {
      console.error('Error fetching timeline and scheduled activity:', error);
    }
  }

  // Fetch last 90 days of statuses for history stats (both devices)
  async function fetchHistoricalStatuses() {
    try {
      const ninetyDaysAgo = Math.floor((Date.now() - (90 * 24 * 60 * 60 * 1000)) / 1000);

      const [oilStatuses, immersionStatuses] = await Promise.all([
        dynamodbClient.getStatuses(stateTableName, OIL, ninetyDaysAgo),
        dynamodbClient.getStatuses(stateTableName, IMMERSION, ninetyDaysAgo)
      ]);

      // Combine and sort all statuses
      const allStatuses = [...oilStatuses, ...immersionStatuses].sort((a, b) => b.since - a.since);
      setStatuses(allStatuses);
    } catch (error) {
      console.error('Error fetching historical statuses:', error);
    }
  }

  // Every run goes through the scheduler lambda, which picks the state machine to drive it.
  async function startRun(device, {startTime = '0', durationSeconds, dhwTargetTemperature, recurring = false}) {
    const params = {
      FunctionName: startScheduleStateChangeLambdaArn,
      Payload: JSON.stringify({
        thingName: device,
        startTime,
        durationSeconds,
        dhwTargetTemperature,
        recurring,
        isInitialInvocation: true
      })
    };

    const data = await lambda.send(new InvokeCommand(params));

    if (data.FunctionError) {
      throw new Error(new TextDecoder().decode(data.Payload));
    }

    await Promise.all([
      fetchTimelineAndScheduledActivity(),
      fetchHistoricalStatuses()
    ]);
    queueRefresh(1500);
  }

  function reportRunFailure(error, message) {
    console.error(message, error);
    if (error.statusCode === 403 || error.$metadata?.httpStatusCode === 403) {
      alert('Forbidden, you must be an authorized user.');
    } else {
      alert(message);
    }
  }

  // Handler for "On for time" action
  async function handleTurnOn(device, durationSeconds) {
    try {
      await startRun(device, {durationSeconds});
    } catch (error) {
      reportRunFailure(error, 'Error turning on heating.');
    }
  }

  // Handler for "On to DHW" action
  async function handleTurnOnToDHW(device, targetTemp) {
    try {
      await startRun(device, {dhwTargetTemperature: targetTemp});
    } catch (error) {
      reportRunFailure(error, 'Error starting temperature run.');
    }
  }

  // Restarting is the only way to lengthen a run: a Wait already counting down cannot be changed.
  async function handleExtend(device, extraSeconds) {
    try {
      const deviceStatus = isOil(device) ? oilStatus : immersionStatus;
      if (!deviceStatus.until) return;

      const remainingSeconds = Math.max(0, deviceStatus.until - Math.floor(Date.now() / 1000));

      if (deviceStatus.executionArn) {
        await cancelExecution(deviceStatus.executionArn);
      }

      await startRun(device, {durationSeconds: remainingSeconds + extraSeconds});
    } catch (error) {
      reportRunFailure(error, 'Error extending heating.');
    }
  }

  // Handler for Schedule action
  function handleSchedule(device) {
    setSelectedDevice(device);
    setScheduleModalShow(true);
  }

  // Handler for Turn Off action
  async function handleTurnOff(device) {
    try {
      // Get the current status for this device
      const deviceStatus = isOil(device) ? oilStatus : immersionStatus;

      // Also check scheduled activity for this device (includes DHW activities)
      const currentActivity = scheduledActivity.find(
        activity => activity.device === device && !activity.until
      );

      const executionArnToCancel = deviceStatus.executionArn || currentActivity?.executionArn;

      if (executionArnToCancel) {
        // Check if this execution belongs to a recurring scheduled activity
        const isRecurring = scheduledActivity.some(
          activity => activity.executionArn === executionArnToCancel && activity.recurring
        );

        if (!isRecurring) {
          // Cancel the execution (works for both scheduled and DHW temperature-based)
          await cancelExecution(executionArnToCancel);
          console.log('Cancelled execution:', executionArnToCancel);
        } else {
          console.log('Not cancelling recurring execution:', executionArnToCancel);
        }
      }

      // Update thing shadow to turn off the heating
      const params = {
        thingName: device,
        shadowName: device + '_shadow',
        payload: new TextEncoder().encode('{"state":{"desired":{"on":false}}}')
      };

      await iotData.send(new UpdateThingShadowCommand(params));

      const status = statusHelper.createStatus(device, modes.OFF.val, {
        endReason: endReasons.STOPPED_MANUALLY
      });
      await dynamodbClient.insertStatus(stateTableName, status);

      await Promise.all([
        fetchTimelineAndScheduledActivity(),
        fetchHistoricalStatuses()
      ]);
    } catch (error) {
      console.error('Error turning off:', error);
      if (error.statusCode === 403 || error.$metadata?.httpStatusCode === 403) {
        alert('Forbidden, you must be an authorized user.');
      } else {
        alert('Error turning off heating.');
      }
    }
  }

  // Handler for Schedule modal confirm
  async function handleScheduleConfirm({startTime, durationSeconds, dhwTargetTemperature, recurring}) {
    try {
      await startRun(selectedDevice, {
        startTime: hoursMinsToISOString(startTime),
        durationSeconds,
        dhwTargetTemperature,
        recurring
      });
      setScheduleModalShow(false);
    } catch (error) {
      reportRunFailure(error, 'Error scheduling heating.');
    }
  }

  function handleScheduleCancel() {
    setScheduleModalShow(false);
    setSelectedDevice(null);
  }

  async function cancelExecution(executionArn) {
    try {
      await stepFunctionsClient.stopRunningExecution(executionArn);
      console.log('Cancelled execution:', executionArn);
    } catch (error) {
      console.error('Error cancelling execution:', error);
      if (error.statusCode === 403 || error.$metadata?.httpStatusCode === 403) {
        alert('Forbidden, you must be an authorized user.');
      } else {
        alert('Error cancelling execution.');
      }
    }
  }

  function handleViewStats(device) {
    setSelectedStatsDevice(device === selectedStatsDevice ? null : device);
  }

  async function handleDeleteScheduled(activity) {
    try {
      await cancelExecution(activity.executionArn);
      await dynamodbClient.delete(scheduleTableName, activity.device, activity.since);
      await fetchTimelineAndScheduledActivity();
    } catch (error) {
      console.error('Error deleting scheduled activity:', error);
      alert('Error deleting scheduled activity.');
    }
  }

  // Accounts are approved by hand and Cognito sends no code, so the confirm-code step it would
  // otherwise land on can never be completed. Report sign-up done and send them back to sign-in.
  const authServices = {
    async handleSignUp(input) {
      const result = await signUp(input);
      setSignUpPending(true);
      return {...result, isSignUpComplete: false, nextStep: {signUpStep: 'DONE'}};
    }
  };

  return (
    <div id="root">
      {signUpPending && (
        <div className="signup-pending" role="status">
          Your request has been sent to Otis for approval. You will be able to sign in once your
          account is approved.
        </div>
      )}
      <Authenticator services={authServices}/>
      <div id="homethermostat">
        {/* Header */}
        <Header
          connected={connected}
          outsideTemp={outsideTemp}
          dhwTemperature={dhwTemperature}
          onDhwClick={() => setShowDhwGraph(true)}
        />

        {/* Timeline */}
        <TimelineChart
          statuses={statuses}
          scheduledActivity={scheduledActivity}
          currentTime={Date.now()}
          onDeleteScheduled={handleDeleteScheduled}
          onStopCurrent={handleTurnOff}
        />

        {/* Device Cards */}
        <DeviceCard
          device={OIL}
          deviceName="Oil"
          status={oilStatus}
          scheduledActivity={scheduledActivity}
          onTurnOn={(duration) => handleTurnOn(OIL, duration)}
          onTurnOnToDHW={(temp) => handleTurnOnToDHW(OIL, temp)}
          onSchedule={() => handleSchedule(OIL)}
          onTurnOff={() => handleTurnOff(OIL)}
          onExtend={(extraSeconds) => handleExtend(OIL, extraSeconds)}
          onViewStats={() => handleViewStats(OIL)}
        />

        {selectedStatsDevice === OIL && (
          <HistoryStats
            statuses={statuses}
            device={OIL}
            deviceName="Oil"
          />
        )}

        <DeviceCard
          device={IMMERSION}
          deviceName="Immersion"
          status={immersionStatus}
          scheduledActivity={scheduledActivity}
          onTurnOn={(duration) => handleTurnOn(IMMERSION, duration)}
          onTurnOnToDHW={(temp) => handleTurnOnToDHW(IMMERSION, temp)}
          onSchedule={() => handleSchedule(IMMERSION)}
          onTurnOff={() => handleTurnOff(IMMERSION)}
          onExtend={(extraSeconds) => handleExtend(IMMERSION, extraSeconds)}
          onViewStats={() => handleViewStats(IMMERSION)}
        />

        {selectedStatsDevice === IMMERSION && (
          <HistoryStats
            statuses={statuses}
            device={IMMERSION}
            deviceName="Immersion"
          />
        )}

        {/* Schedule Modal */}
        <ScheduleModal
          show={scheduleModalShow}
          handleConfirm={handleScheduleConfirm}
          handleCancel={handleScheduleCancel}
        />

        {/* DHW Graph Modal */}
        <DhwGraphModal
          isOpen={showDhwGraph}
          onClose={() => setShowDhwGraph(false)}
          dynamodbClient={dynamodbClient}
          temperatureTableName={temperatureTableName}
          statuses={statuses}
        />
      </div>
    </div>
  );
};

export default App;
